### ISSUE TITLE
Error fetching data, ev.start.getHours not a function

### ISSUE THREAD

**Issue by maksimluzik** [netlight/netlight-calendar#5]
2018-05-16T10:18:43.556111+00:00 app[web.1]: /app/routes/events.js:47
2018-05-16T10:18:43.556114+00:00 app[web.1]:               ev.start = ev.start.setHours(ev.start.getHours() - timezone_offset);
2018-05-16T10:18:43.556116+00:00 app[web.1]:                                                     ^
2018-05-16T10:18:43.556118+00:00 app[web.1]: 
2018-05-16T10:18:43.556121+00:00 app[web.1]:     at /app/routes/events.js:47:53
2018-05-16T10:18:43.556119+00:00 app[web.1]: TypeError: ev.start.getHours is not a function
2018-05-16T10:18:43.556122+00:00 app[web.1]:     at Request._callback (/app/node_modules/ical/node-ical.js:11:5)
2018-05-16T10:18:43.556124+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/request/request.js:187:22)
2018-05-16T10:18:43.556125+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2018-05-16T10:18:43.556130+00:00 app[web.1]:     at Request.emit (events.js:188:7)
2018-05-16T10:18:43.556126+00:00 app[web.1]:     at Request.emit (events.js:191:7)
2018-05-16T10:18:43.556128+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/request/request.js:1048:10)
2018-05-16T10:18:43.556129+00:00 app[web.1]:     at emitOne (events.js:96:13)
2018-05-16T10:18:43.556131+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:969:12)
2018-05-16T10:18:43.556133+00:00 app[web.1]:     at emitNone (events.js:91:20)

**Comment by myrjola** [comment]
The ical library is unable to parse certain dates.

`ev.start` is the string `00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius":20180301T170000`.

Here's an example `VEVENT` that is not parsed correctly and silently fails, i.e., it is not displayed on the calendar.

```ical
BEGIN:VEVENT
UID:040000008200E00074C5B7101A82E00800000000C5278434CEA4D301000000000000000
 0100000007EB6866A9EF1564BB6FAD3528408A087
SUMMARY:Busy
DTSTART;TZID="(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius":2018
 0301T170000
DTEND;TZID="(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius":201803
 01T190000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20180516T112012Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:1
X-MICROSOFT-CDO-APPT-SEQUENCE:1
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
```

```json
{
    "type": "VEVENT",
    "params": [],
    "uid": "040000008200E00074C5B7101A82E00800000000C5278434CEA4D3010000000000000000100000007EB6866A9EF1564BB6FAD3528408A087",
    "summary": "Busy",
    "start": "00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius\":20180301T170000",
    "end": "00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius\":20180301T190000",
    "class": "PUBLIC",
    "priority": "5",
    "dtstamp": "20180516T113139Z",
    "transparency": "OPAQUE",
    "status": "CONFIRMED",
    "sequence": "1",
    "MICROSOFT-CDO-APPT-SEQUENCE": "1",
    "MICROSOFT-CDO-BUSYSTATUS": "BUSY",
    "MICROSOFT-CDO-INTENDEDSTATUS": "BUSY",
    "MICROSOFT-CDO-ALLDAYEVENT": "FALSE",
    "MICROSOFT-CDO-IMPORTANCE": "1",
    "MICROSOFT-CDO-INSTTYPE": "0",
    "MICROSOFT-DONOTFORWARDMEETING": "FALSE",
    "MICROSOFT-DISALLOW-COUNTER": "FALSE",
    "title": "Busy",
    "resourceId": "whole_office"
}
```
I'll see if this bug has been fixed in newer versions of the library.
